language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - composer update --prefer-source
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpcr_tests;"; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database phpcr_tests;" -U postgres; fi
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/DBUnit-1.1.2
  - php tests/generate_phpunit_config.php $DB

script: phpunit -c $DB.phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
# hhvm will fail until libxml support is added https://github.com/facebook/hhvm/issues/1194

notifications:
  irc: "irc.freenode.org#jackalope"
