language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
# duplicate install to work around https://github.com/composer/composer/issues/789
  - composer install --prefer-source
  - composer install --prefer-source --dev
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpcr_tests;"; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database phpcr_tests;" -U postgres; fi
  - pyrus set auto_discover 1
  - pyrus install phpunit/DBUnit-1.1.2
  - php tests/generate_phpunit_config.php $DB

script: phpunit -c $DB.phpunit.xml

notifications:
  irc: "irc.freenode.org#jackalope"
