language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=mysql PACKAGE_VERSION=high
  - DB=mysql PACKAGE_VERSION=low
  - DB=pgsql PACKAGE_VERSION=high
  - DB=pgsql PACKAGE_VERSION=low
  - DB=sqlite PACKAGE_VERSION=high
  - DB=sqlite PACKAGE_VERSION=low

before_script:
  - composer selfupdate
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-source --no-interaction; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-source --no-interaction; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpcr_tests;"; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database phpcr_tests;" -U postgres; fi
  - php tests/generate_phpunit_config.php $DB

script: phpunit -c $DB.phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
# hhvm will fail until libxml support is added https://github.com/facebook/hhvm/issues/1194

notifications:
  irc: "irc.freenode.org#jackalope"
