language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - composer update --prefer-source
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpcr_tests;"; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database phpcr_tests;" -U postgres; fi
  - php tests/generate_phpunit_config.php $DB

script: phpunit -c $DB.phpunit.xml

notifications:
  irc: "irc.freenode.org#jackalope"
