language: php

php:
  - 5.3
  - 5.4

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

before_script:
  - curl -s http://getcomposer.org/installer | php
# duplicate install to work around https://github.com/composer/composer/issues/789
  - php composer.phar install
  - php composer.phar install --dev
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpcr_tests;"; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database phpcr_tests;" -U postgres; fi
  - pyrus install phpunit/DBUnit
  - tests/generate_travis_config.php

script: phpunit

notifications:
  irc: "irc.freenode.org#jackalope"
